language: ruby
rvm:
  - 1.9.3
  #- 2.0.0
env:
  - DB=sqlite
  #- DB=mysql
  #- DB=postgresql
script:
  - RAILS_ENV=test
  - cd dummy
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - cd ..
  - bundle exec rake test