language: ruby
rvm:
  - 1.9.3
  #- 2.0.0
env:
  - DB=sqlite
  #- DB=mysql
  #- DB=postgresql
script:
  - RAILS_ENV=test
  - sh -c 'cd test/dummy' && bundle exec rake db:drop db:create db:migrate db:seed test
  - sh -c 'cd ../..' && bundle exec rake test