language: ruby
cache: bundler
rvm:
  - 1.9.3
  #- 2.0.0
env:
  - DB=sqlite
  #- DB=mysql
  #- DB=postgresql
script:
  - RAILS_ENV=test
  - cd ./test/dummy
  - bundle exec rake db:drop db:create db:migrate db:seed test
  - cd ../..
  - bundle exec rake test